CREATE TABLE [dbo].[DEPARTMENTS] (
    [Id] int NOT NULL CONSTRAINT [DF_DEPARTMENTS_Id] DEFAULT (NEXT VALUE FOR [dbo].[DepartmentIdSequence]),
    [Name] nvarchar(120) NOT NULL,
    CONSTRAINT [PK_DEPARTMENTS] PRIMARY KEY ([Id])
);

GO

CREATE UNIQUE INDEX [IX_DEPARTMENTS_Name]
    ON [dbo].[DEPARTMENTS] ([Name]);
